version: '3'

services:

  connect:
    container_name: connect
    image: darren0609/connect:v1
    hostname: connect
    build:
      context: .
      dockerfile: dockerfile
    environment:
      GET_HOSTS_FROM: dns
    networks:
    - connectnet
    volumes:
    - .:/go/src/main
    ports:
    - 8090:8090
    
    labels:
      kompose.service.type: LoadBalancer

networks:
  connectnet:
    driver: bridge
